### ISSUE TITLE
Display unplanned bugs on top of the backlog

### ISSUE THREAD

**Issue by 1602** [1602/issues-tracker#3]
In order to track unplanned stories caused by technical debt not paid on time, we should have the ability to label stories with `Type: bug` label and display it on top of the backlog until it is started by someone.

The new rule is: if an issue has no milestone and labeled with `Type: Bug` or `bug` and not labeled with "Status: In progress", then it should be displayed on top of the backlog.

**Comment by mprussell** [comment]
Question: Can low-priority bugs be assigned to a Milestone (and therefore not be pinned to the top of Backlog)? I guess so, just asking for clarity.
